version: 0.2

phases:
  install:
    commands: # installing panorama cli
      - aws --version
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands: # TODO: download from S3 and upload to S3, rmb to grant S3 access to IAM.
      - echo $PRETRAIN_BUCKET 
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - export ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - cd script
      - aws s3 cp training-input/ $PRETRAIN_BUCKET --recursive
      - bash matlab_pull_and_push.sh ap-southeast-1
      - bash yolov5_pull_and_push.sh ap-southeast-1

      - export Function_Name="metricToPicture-${env}"
      - >
        aws lambda create-function \
        --function-name $Function_Name \
        --package-type Image
        --code '{
          "ImageUri": "'$ACCOUNT_ID'.dkr.ecr.ap-southeast-1.amazonaws.com/python39-matplotlib-lambda:latest"
        }' \
  post_build:
    commands:
      - echo Build completed on `date`
      # - aws stepfunctions send-task-failure --task-token $TASK_TOKEN 
  
  
