version: 0.2

phases:
  install:
    commands: # installing panorama cli
      - aws --version
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands: # TODO: download from S3 and upload to S3, rmb to grant S3 access to IAM.
      - echo $PRETRAIN_BUCKET 
      - echo $REGION
      - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - cd script
      - aws s3 cp training-input/ $PRETRAIN_BUCKET --recursive
      - cd ..
      - cd deployment
      - zip ppe_panorama_app ppe_panorama_app 
      - ls
      - aws s3 cp ppe_panorama.zip $APP_BUCKET
      - bash matlab_pull_and_push.sh $REGION 
      - bash yolov5_pull_and_push.sh $REGION 

  post_build:
    commands:
      - echo Build completed on `date`
      # - aws stepfunctions send-task-failure --task-token $TASK_TOKEN 
  
  
